## Example Config file
baseURL: "https://example.com"
theme: "terminalcv"
title: "terminalcv"

params:
  version: '2.0.0'
  description: "My terminal cv"
  prompt:
    core:
      text: "user@terminalCV"
      color: 'pink'
      #before: '['
      beforeColor: 'red'
      #after: '\]'
      afterColor: 'red'
      # separator: '-'
    separator:
      text: "-"
      # color: 
    path: 
      before: '['
      beforeColor: 'red'
      text: '~/terminalcv'
      color: 'lightblue'
      after: '\]'
      afterColor: 'red'
    extra:
      text: ": "
      color: 'orange'

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  exitLocation: 'about:blank'
  source: true
  #use a ‎ (blank character) if your first character of the ascii art is a whitespace
  greeting: | 
    ‎ _                      _             _  _______      __
    | |                    (_)           | |/ ____\ \    / /
    | |_ ___ _ __ _ __ ___  _ _ __   __ _| | |     \ \  / / 
    | __/ _ \ '__| '_ ` _ \| | '_ \ / _` | | |      \ \/ /  
    | ||  __/ |  | | | | | | | | | | (_| | | |____   \  /   
     \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_|\_____|   \/

    Welcome to my online resume

    Type 'help' for a list of available commands


  whoami: 
    # settings:
    #   useLess: true
    details:
      name: "Bassam Khan"
      profession: "Cybersecurity Engineer"
      location: "Pakistan"
      email: "bassam.exe@gmail.com"
      homelink: "https://snowdensvault.fyi"
      description: |
              Avid CTF player with a passion for reverse engineering, OSINT, web & app pentesting, SOC analysis, and malware & exploit development.
              Off-duty, you'll find me lost in books, mastering chess, gaming, editing videos, or animating. Always chasing the next challenge! 🚀

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
    - name: "github"
      url: "https://github.com/MasterChief220"
    - name: "medium"
      url: "https://medium.com/@bassam-khan"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/mbassamkhan/"
    - name: "tryhackme"
      url: "https://tryhackme.com/p/bassam.exe"

  work:
    # settings:
    #   useLess: true
    details:
    - jobTitle: Assistant Executive Engineer - Cybersecurity
      color: red
      company: 'National Radio and Telecommunication Corporation' 
      location: Islamabad, Pakistan
      date: September 2024 - Present
      description: |
        1. Configured and deployed EDR, NDR, SIEM, and SOAR solutions at NCERT, including setting up the network and servers for hosting the tools.
        2. Analyzed malware behavior and signatures using open-source tools for threat detection.
        3. Investigated phishing links, examining websites and redirections for security risks.
        4. Conducted penetration testing and vulnerability assessments on websites and servers to identify and remediate security weaknesses.

    - jobTitle: Intern
      color: purple
      company: 'Lucky Power'
      location: Karachi, Pakistan
      date: July 2024  - August 2024
      description: |
       1. Completed a 6-week internship at Lucky Power Plant under Harbin Electric’s O&M contract, gaining hands-on experience in coal handling, water treatment, flue gas desulfurization, and boiler-turbine-generator operations.
       2. Operated and studied an ultra-supercritical boiler, including its start-up procedure, coal handling with stacker-reclaimer, and the role of IDF and FDF fans in maintaining boiler functionality.
       3. Acquired knowledge in water treatment processes, such as seawater intake and chemical testing (oxygen bomb testing, proximate analysis), and observed flue gas desulfurization using limestone slurry to produce gypsum.
       4. Developed a comprehensive understanding of operations in a 660 MW power plant, focusing on efficiency and safety protocols.

    - jobTitle: Intern
      color: green
      company: 'Fauji Foundation'
      location: Rawalpindi, Pakistan
      date: August 2023 - September 2023
      description: |
        1. Completed a networking/cybersecurity internship, gaining expertise in OSI layers, routing, routed protocols, VTP, STP, Ethernet cables, subnetting, and network segmentation.
        2. Designed a detailed network layout using Microsoft Visio and drafted a bill of quantity in Excel for network setup, ensuring accurate representation and configuration planning.
        3. Simulated network architecture in Packet Tracer, configuring switches, routers, VLANs, trunking lines, and STP protocols for optimal functionality.
        4. Conducted security assessments using Wireshark, Nmap, Traceroute, and Aircrack to analyze network packets, identify vulnerabilities, and strengthen network defenses.

  education:
    details:
    - courseName: NUST
      color: blue
      date: September 2020 - June 2024
      description: Mechatronics Engineering

    - courseName: Nixor College
      color: red
      date: August 2018 - Jun 2020
      description: Maths, Physics, Chemistry

  skills:
    settings:
      useLess: false
    details:
    - name: Web Pentesting
      percentage: 50
      description: Comfortable with Burp Suite, SQL Injection, XSS, SSRF, IDOR

    - name: Network Pentesting
      percentage: 45
      description: Experience with Nmap, Wireshark, Metasploit, Traceroute, SNMP enumeration

    - name: Malware Analysis
      percentage: 30
      description: Learning static and dynamic analysis, working with malware sandboxes

    - name: Reverse Engineering
      percentage: 25
      description: Basic knowledge of assembly, Ghidra, and IDA Free

    - name: Digital Forensics
      percentage: 30
      description: Beginner in disk forensics, memory analysis, and file carving

    - name: Web Scraping & Automation
      percentage: 60
      description: Intermediate in Selenium, BeautifulSoup, Scrapy, Puppeteer

    - name: Programming
      percentage: 70
      description: Comfortable in Python, Bash, C++, MySQL, Microcontroller Programming

    - name: Machine Learning
      percentage: 35
      description: Beginner in regression, classification, OpenCV, TensorFlow, Scikit-learn

    - name: Engineering Tools
      percentage: 50
      description: Experience with AutoCAD, LabVIEW, MATLAB, Proteus, RsLogix

  softskills:
    # settings:
    #   useLess: true
    details:
    - name: Problem Solving
      percentage: 75
      description: Strong analytical thinking and troubleshooting skills in different scenarios

    - name: Communication
      percentage: 65
      description: Ability to explain technical concepts clearly to non-technical audiences

    - name: Teamwork & Collaboration
      percentage: 70
      description: Experience working in SOC teams, collaborating with IT and security professionals

    - name: Adaptability
      percentage: 80
      description: Quickly learns new technologies, tools, and  methodologies

    - name: Critical Thinking
      percentage: 75
      description: Strong ability to analyze patterns and detect flaws effectively

  languages:
    # settings:
    #   useLess: true
    details:
    - name: English
      #color: Blue
      percentage: 100
      #description: 

    - name: Urdu
      percentage: 80
      #description: pasghettipigglywiggly


  projects:
    # settings:
    #   useLess: true
    details:
    - title: Computer Vision Car Counter
      color: blue
      date: 2023
      link: https://github.com/MasterChief220/Computer-Vision-Car-Counter
      description: A project for detecting and counting cars in video frames using Image Processing techniques. Utilizes a pre-trained Haar Cascade Classifier for accurate car detection. Built with OpenCV and Python.

    - title: Qalam Form Filler
      color: green
      date: 2024
      link: https://github.com/MasterChief220/qalam-form-filler
      description: A Python script leveraging Selenium for automated interaction with the Qalam NUST portal. Automates login, form navigation, and button clicks using web element identification and dynamic waits.

    - title: ELK SIEM
      color: red
      date: 2024
      link: https://bassamkhan.netlify.app/#
      description: Set up Elastic Stack (Elasticsearch and Kibana) to centralize logs from Linux and Windows machines. Configured Auditbeat and Winlogbeat for log collection, enabling real-time analysis and security monitoring.


  certifications:
    # settings:
    #   useLess: true
    details:
    - certName: SOC Level 1 Certificate
      company: TryHackMe
      date: Jan 2025
      badge:  https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-VAFQPBPHL0.pdf
      description: Certified in Security Operations Center (SOC) Level 1, covering SIEM tools, network security, and incident detection.

    - certName: Networking Basics
      company: Cisco
      date: Oct 2024
      badge: https://www.credly.com/badges/f7f24b92-fe6f-4240-86dd-0767c8e1ef08/linked_in_profile
      description: Completed a fundamental networking course covering network security, routing, switching, and TCP/IP.

    - certName: Python, Bash, and SQL Essentials for Data Engineering
      company: Coursera
      date: Oct 2023
      badge: https://www.coursera.org/account/accomplishments/specialization/certificate/5HD4Y9T3XDXP
      description: Covered Python, Bash scripting, SQL, web scraping, and data engineering techniques.

    - certName: Developing Front-End Apps with React
      company: Coursera
      date: Sep 2023
      badge: https://www.coursera.org/account/accomplishments/certificate/HT5GEEFJ645R
      description: Learned React.js for front-end web development, including state management and component-based architecture.

    - certName: Google Cybersecurity Certificate
      company: Coursera
      date: Sep 2023
      badge: https://www.credly.com/badges/2c389484-5213-4319-8a84-9d24a0bc6405/linked_in_profile
      description: Covered security frameworks, SIEM tools, incident response, and Linux system security.

    - certName: Getting Started with Git and GitHub
      company: Coursera
      date: Aug 2023
      badge: https://www.coursera.org/account/accomplishments/certificate/BWCMLWEQ8SZ5
      description: Fundamental training on Git version control and GitHub for repository management.

    - certName: Introduction to Bash Shell Scripting
      company: Coursera
      date: Aug 2023
      badge: https://www.coursera.org/account/accomplishments/certificate/AAR8PQR7932E
      description: Introduction to writing and automating tasks using Bash scripting.

    - certName: Introduction to Cloud Computing
      company: Coursera
      date: Aug 2023
      badge: https://www.coursera.org/account/accomplishments/certificate/WB4QE6HS9KR4
      description: Covered cloud computing fundamentals, including cloud deployment models and services.

    - certName: Junior Penetration Tester
      company: TryHackMe
      date: Aug 2023
      badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-0H8WMX92SB.png
      description: Covered penetration testing techniques including privilege escalation, SQL injection, web vulnerabilities, and Metasploit.

    - certName: Ethical Hacking Essentials (EHE)
      company: EC-Council
      date: Jul 2023
      badge: https://codered.eccouncil.org/certificate/f3d074c4-defe-447a-b98d-46df0a8b100a
      description: Basic ethical hacking certification covering penetration testing methodologies.

    - certName: Introduction to Cybersecurity
      company: TryHackMe
      date: Jul 2023
      badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-9D12ZWBCVI.png
      description: Introduction to cybersecurity concepts including network security and risk assessment.

    - certName: Introduction to Quantum Computing
      company: Udemy
      date: Jul 2023
      badge: https://www.udemy.com/certificate/UC-7cc5659d-8ec2-4911-82ad-bead45bebda9/
      description: Covered foundational quantum computing concepts.

    - certName: Introduction to Web Development with HTML, CSS, JavaScript
      company: Coursera
      date: Jul 2023
      badge: https://www.coursera.org/account/accomplishments/certificate/6H6WLHM3FNWN
      description: Covered front-end web development using HTML, CSS, and JavaScript.

    - certName: Pre-Security Learning Path
      company: TryHackMe
      date: Jul 2023
      badge: https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-OPGALNQOOV.png
      description: Covered cybersecurity fundamentals including networking, Linux, and web security.

    - certName: Reverse Engineering .NET for Beginners (Visual Basic)
      company: Udemy
      date: Jul 2023
      badge: https://www.udemy.com/certificate/UC-603f4b94-05d9-4098-8bd0-82de2adb5155/
      description: Introduction to reverse engineering .NET applications.

    - certName: Supervised Machine Learning- Regression and Classification
      company: Coursera
      date: Jun 2023
      badge: https://coursera.org/share/2f8f4d42cc8da8e2f0b68c42888e0470
      description: Covered machine learning fundamentals including regression and classification.
  
  misc:
    commandName: links
    title: "My Digital Presence"
    titleColor: teal
    content: |
         Explore my work and projects through the following links:

          🔸 Cybersecurity & Tech Blog:  
             https://blog.snowdensvault.fyi/ 
             – In-depth articles on cybersecurity, pentesting, and more.  

          🔹 Portfolio:  
             https://bassamkhan.netlify.app/  
             – A streamlined overview of my skills, projects, and certifications.  

          🔷 Main Website:  
             https://snowdensvault.fyi/  
             – The central hub for everything I do.  

          Stay connected and explore my work!
    contentColor: white
