## Example Config file
baseURL: "https://example.com"
theme: "terminalcv"
title: "terminalcv"

params:
  version: '2.0.0'
  description: "My terminal cv"
  prompt:
    core:
      text: "user@terminalCV"
      color: 'pink'
      before: '['
      beforeColor: 'red'
      after: '\]'
      afterColor: 'red'
      # separator: '-'
    separator:
      text: "-"
      # color: 
    path: 
      before: '['
      beforeColor: 'red'
      text: '~/terminalcv'
      color: 'blue'
      after: '\]'
      afterColor: 'red'
    extra:
      text: ": "
      color: 'orange'

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  exitLocation: 'about:blank'
  source: true
  #use a ‎ (blank character) if your first character of the ascii art is a whitespace
  greeting: | 
    ‎ _                      _             _  _______      __
    | |                    (_)           | |/ ____\ \    / /
    | |_ ___ _ __ _ __ ___  _ _ __   __ _| | |     \ \  / / 
    | __/ _ \ '__| '_ ` _ \| | '_ \ / _` | | |      \ \/ /  
    | ||  __/ |  | | | | | | | | | | (_| | | |____   \  /   
     \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_|\_____|   \/

    Welcome to my online resume

    Type 'help' for a list of available commands


  whoami: 
    # settings:
    #   useLess: true
    details:
      name: "Bassam Khan"
      profession: "Cybersecurity Engineer"
      location: "Pakistan"
      email: "bassam.exe@gmail.com"
      homelink: "https://snowdensvault.fyi"
      description: |
              Avid CTF player with a passion for reverse engineering, OSINT, web & app pentesting, SOC analysis, and malware & exploit development.
              Off-duty, you'll find me lost in books, mastering chess, gaming, editing videos, or animating. Always chasing the next challenge! 🚀

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
    - name: "github"
      url: "https://github.com/MasterChief220"
    - name: "medium"
      url: "https://medium.com/@bassam-khan"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/mbassamkhan/"
    - name: "tryhackme"
      url: "https://tryhackme.com/p/bassam.exe"

  work:
    # settings:
    #   useLess: true
    details:
    - jobTitle: Assistant Executive Engineer - Cybersecurity
      color: red
      company: 'National Radio and Telecommunication Corporation' 
      location: Islamabad, Pakistan
      date: September 2024 - Present
      description: |
        1. Configured and deployed EDR, NDR, SIEM, and SOAR solutions at NCERT, including setting up the network and servers for hosting the tools.
        2. Analyzed malware behavior and signatures using open-source tools for threat detection.
        3. Investigated phishing links, examining websites and redirections for security risks.
        4. Conducted penetration testing and vulnerability assessments on websites and servers to identify and remediate security weaknesses.

    - jobTitle: Intern
      color: purple
      company: 'Lucky Power'
      location: Karachi, Pakistan
      date: July 2024  - August 2024
      description: |
       1. Completed a 6-week internship at Lucky Power Plant under Harbin Electric’s O&M contract, gaining hands-on experience in coal handling, water treatment, flue gas desulfurization, and boiler-turbine-generator operations.
       2. Operated and studied an ultra-supercritical boiler, including its start-up procedure, coal handling with stacker-reclaimer, and the role of IDF and FDF fans in maintaining boiler functionality.
       3. Acquired knowledge in water treatment processes, such as seawater intake and chemical testing (oxygen bomb testing, proximate analysis), and observed flue gas desulfurization using limestone slurry to produce gypsum.
       4. Developed a comprehensive understanding of operations in a 660 MW power plant, focusing on efficiency and safety protocols.

    - jobTitle: Intern
      color: green
      company: 'Fauji Foundation'
      location: Rawalpindi, Pakistan
      date: August 2023 - September 2023
      description: |
        1. Completed a networking/cybersecurity internship, gaining expertise in OSI layers, routing, routed protocols, VTP, STP, Ethernet cables, subnetting, and network segmentation.
        2. Designed a detailed network layout using Microsoft Visio and drafted a bill of quantity in Excel for network setup, ensuring accurate representation and configuration planning.
        3. Simulated network architecture in Packet Tracer, configuring switches, routers, VLANs, trunking lines, and STP protocols for optimal functionality.
        4. Conducted security assessments using Wireshark, Nmap, Traceroute, and Aircrack to analyze network packets, identify vulnerabilities, and strengthen network defenses.

  education:
    details:
    - courseName: NUST
      color: blue
      date: September 2020 - June 2024
      description: Mechatronics Engineering

    - courseName: Default color training
      date: Sept 2004 - Jun 2008
      #description: There is no need for description

  skills:
    settings:
      useLess: true
    details:
    - name: Skill 1
      percentage: 90
      Description: you can add a description

    - name: Skill 2
      percentage: 30
      #description: or you can leave it comented   

    - name: Skill 3
      color: blue
      percentage: 50
      description: Skill names can have colors too

  softskills:
    # settings:
    #   useLess: true
    details:
    - name: SoftSkill 1
      color: red
      percentage: 80
      #description:

    - name:  SoftSkill 2
      #color: 
      percentage: 90
      description: Description

  languages:
    # settings:
    #   useLess: true
    details:
    - name: English
      color: Blue
      percentage: 50
      #description: 

    - name: Gibberish
      percentage: 100
      description: pasghettipigglywiggly


  projects:
    # settings:
    #   useLess: true
    details:
    - title: Project Red
      color: red
      date: since 2019
      link: https://example.com
      description: Describing red stuff

    - title: Project Blue
      color: blue
      date: since 2016
      link: https://example.com/blue
      #description: nothing to describe

    - title: Project Default
      date: Since 2017
      link: https://example.com/default
      #description: not there either

  certifications:
    # settings:
    #   useLess: true
    details:
    - certName: Example Cert
      company: Example Certifying Company
      date: Date of Completion
      badge: https://www.link.to.badge
      #description: Lorem Ipsum
  
  misc: 
    # settings:
    #   useLess: true
    commandName: newcommand
    title: "This Section can have a different command name"
    titleColor: teal
    content: |
          Here the title and the content can have different colors
          The content can be multi
          
          line

          And spaces       will be respected as well
          This section will have the default command: misc
          but you can name it something else with the property
          commandName: <String>
          Give it a shot and try and uncomment the line 
          commandName: newcommand
          now instead of misc you can execute the newcommand for this section
          Auto completion will know it too! :D 

    contentColor: orange
